provider:
  name: faas
  provider: faas
  gateway: http://68.183.211.211:31112

functions:
  youtubedl:
    lang: Dockerfile
    handler: ./
    image: albertomarini/faas-youtubedl:0.3
    constraints:
       - "type=amazing"
