provider:
  name: faas
  provider: openfaas
  gateway: http://165.227.245.168:31112/

functions:
  youtubedl:
    lang: Dockerfile
    handler: ./
    image: albertomarini/faas-youtubedl:0.3
    constraints:
       - "type=rspbpi-01"
